version: '3'
services:
  myapp:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - redis
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: uvicorn app:app --host 0.0.0.0 --port 8000

  rabbitmq:
    image: "rabbitmq:3.8"
    ports:
      - "5672:5672"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    restart: unless-stopped  # Evita que Redis se reinicie automáticamente


