version: '3'
services:
  myapp:
    build: ./app
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - redis
      - celery  # Agrega dependencia a celery para que espere su disponibilidad
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@srv.ibc.bio:32837//
      - CELERY_RESULT_BACKEND=redis://srv.ibc.bio:32828/0
    command: uvicorn app:app --host 0.0.0.0 --port 8000

  rabbitmq:
    image: "rabbitmq:3.8"
    ports:
      - "5672:5672"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    restart: unless-stopped

  celery:
    build: ./celery_worker  # Ruta al Dockerfile del servicio de Celery
    depends_on:
      - rabbitmq
      - redis
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@srv.ibc.bio:32837//
      - CELERY_RESULT_BACKEND=redis://srv.ibc.bio:32828/0
    command: celery -A celery_worker.celery worker --loglevel=info


